### ISSUE TITLE
Feature - Create a simple car

### ISSUE THREAD

**Issue by harshit211997** [harshit211997/Car#1]
### Tasks
- [ ] Learn the different ways the car mechanics can be defined(#3)
- [ ] Create or download a car model which looks minimal(#2)
- [ ] Make the car mechanics as fun as possible(#4)
- [ ] Set up environment elements(#5)
